// vue/vue07/vuexdemo/src/vuexdemo_基本使用/Son1.vue
<template>
  <div>
     <h4>子组件1</h4>
     name:{{this.$store.state.name}}
     <br>
     age:{{this.$store.state.age}}
     <button @click='change'>改年龄</button>
  </div>
</template>
<script>
export default {
  methods: {
    change(){
      // dispatch 用来触发acition里的函数
      this.$store.dispatch('changeAgeAction',{age:777})
    }
  },
}
</script>

// react/react05/src/ReactRedux copy/Son1.js
import React, { Component } from 'react';
import {connect} from 'react-redux'
import {bindActionCreators} from 'redux'
import actionCreator from './store/actionCreator';
class Son1 extends Component {

  render() { 
    let {name,age} = this.props
    return ( 
      <div>
        <h3>大儿子</h3>
        {name}
        {age}
        <button onClick={()=>{
         this.props.CHANGE_NAME()
        }}>改名</button>
      </div>
     );
  }
}
 
export default connect(state=>state,(dispatch)=>{
  return bindActionCreators(actionCreator,dispatch)
})(Son1);
