// react/react05/src/ReactRedux copy/Box.js
import React, { Component } from 'react';
import Son1 from "./Son1"
import Son2 from "./Son2"
class Box extends Component {
  state = {  }
  render() { 
    return ( 
      <div>
        <h3>react-redux使用</h3>
        <Son1></Son1>
        <hr/>
        <Son2></Son2>
      </div>
     );
  }
}
 
export default Box;

// vue/vue07/vuexdemo/src/vuexdemo_基本使用/Box.vue

<template>
  <div>
     <h4>这里是盒子组件 {{this.$store.state.name}}</h4>
     getters:{{this.$store.getters.double}}
     <son1></son1>
     <hr>
     <son2></son2>
  </div>
</template>
<script>
import Son1 from './Son1'
import Son2 from './Son2'
export default {
  name:'Box',
  components:{Son1,Son2},
  mounted() {
    console.log(this.$store.state.name)
  },
}
</script>
