// react/react04/src/Redux_简易优化/Son2.js
import React, { Component } from 'react';
import ActionCreator from './store/actionCreator'
import connect from './connect'
class Son2 extends Component {

  render() {  
    let {name,age} = this.props

    return (  
      <div>
        <h3>子组件2</h3>
        name:{name}
        <br/>
        age:{age}
        <button onClick={()=>{
          ActionCreator.changeName('隔壁王叔叔')
        }}>改名</button>
      </div>
    );
  }
}
 
export default connect(Son2);

// vue/vue07/vuexdemo/src/vuexdemo_基本使用/Son2.vue
<template>
  <div>
     <h4>子组件2</h4>
     name:{{this.$store.state.name}}
     <button @click='change'>改名</button>
    <br>
     age:{{this.$store.state.age}}
  </div>
</template>
<script>
export default {
  methods: {
    change(){
      // 通过commit方法触发mutation 
      // 参数1 要触发的方法名
      // 参数2 是要传递的数据
      this.$store.commit('changeName',{name:123,pass:456})
    }
  },
   mounted() {
    console.log('组件2',this) 
   }
}
</script>
